# Based on http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html
# Tweaked to specify versions on everything for stability.
language: python
python:
  - "3.6"

cache: apt

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Prefer stability to having the latest
  #- conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy==0.19.2
  - pip install -r requirements.txt

script:
  - python test.py
